export const classes=['Computer Science','Mathematics','Physics','Statistics','Quantitative Biology','Quantitative Finance','Electrical Engineering','Economics'];
export type Paper={id:string,title:string,authors:string,abstract:string,targetClass:string,year:number,citations:number,pages:number};
export const papers:Paper[]=[
{id:'1910.11924',title:'A Calculus for Language Transformations',authors:'Benjamin Mourad, Matteo Cimini',abstract:'We propose a calculus for expressing algorithms for programming language transformations, with a focus on compositional reasoning and operational semantics.',targetClass:'Computer Science',year:2019,citations:182,pages:18},
{id:'1706.03762',title:'Attention Is All You Need',authors:'Ashish Vaswani, Noam Shazeer, Niki Parmar et al.',abstract:'The dominant sequence transduction models are based on complex recurrent or convolutional neural networks. We propose a simple network architecture, the Transformer, based solely on attention mechanisms.',targetClass:'Computer Science',year:2017,citations:94521,pages:15},
{id:'1905.02134',title:'Photon-Photon Interactions in Dynamically Coupled Cavities',authors:'Research Collaboration',abstract:'We study theoretically the interaction between two photons in a nonlinear cavity and analyze several nonlinearities relevant to cavity-enhanced light-matter interactions.',targetClass:'Physics',year:2019,citations:241,pages:13},
{id:'1810.01509',title:'Hierarchical Community Detection by Recursive Partitioning',authors:'Tianxi Li, Lihua Lei, Sharmodeep Bhattacharyya et al.',abstract:'We argue that it is more interpretable and in some regimes more accurate to construct a hierarchical tree of communities using recursive spectral partitioning.',targetClass:'Statistics',year:2018,citations:319,pages:28},
{id:'1912.11576',title:'On the Coverage and Capacity of Ultra-Dense Networks with Directional Transmissions',authors:'Yining Xu, Sheng Zhou',abstract:'We investigate a downlink ultra-dense network with directional transmissions via stochastic geometry, deriving coverage and constrained area spectrum efficiency characteristics.',targetClass:'Electrical Engineering',year:2019,citations:77,pages:16},
{id:'1906.11430',title:'Horndeski Model in Nonlinearly Realized Supergravity',authors:'Yusuke Yamada, Junichi Yokoyama',abstract:'We construct the Horndeski Lagrangian within non-linearly realized supergravity and analyze the resulting bosonic and gravitino couplings.',targetClass:'Physics',year:2019,citations:104,pages:11},
{id:'2002.03089',title:'The First VERA Astrometry Catalog',authors:'VERA Collaboration',abstract:'We present the first astrometry catalog from the Japanese VLBI project VERA, compiling astrometry results and comparing them with other Galactic surveys.',targetClass:'Physics',year:2020,citations:148,pages:24}];
export type Model={name:string,type:string,macroF1:number,accuracy:number,weightedF1:number,description:string};
export const models:Model[]=[
{name:'Weighted Ensemble',type:'Ensemble',macroF1:.7143,accuracy:.8865,weightedF1:.8898,description:'Weighted combination of BERT, Logistic Regression and BiGRU.'},
{name:'BERT Base',type:'Transformer',macroF1:.7051,accuracy:.8817,weightedF1:.8846,description:'Transformer classifier fine-tuned for discipline prediction.'},
{name:'Logistic Regression',type:'Classical ML',macroF1:.5698,accuracy:.8576,weightedF1:.8613,description:'TF-IDF features with regularized logistic regression.'},
{name:'BiGRU',type:'Deep Learning',macroF1:.5674,accuracy:.8090,weightedF1:.8312,description:'Bidirectional GRU using Word2Vec embeddings.'},
{name:'BiLSTM',type:'Deep Learning',macroF1:.5500,accuracy:.7950,weightedF1:.8192,description:'Bidirectional LSTM sequence classifier.'},
{name:'GRU',type:'Deep Learning',macroF1:.5475,accuracy:.7855,weightedF1:.8174,description:'GRU sequence classifier using Word2Vec embeddings.'},
{name:'Random Forest',type:'Classical ML',macroF1:.5459,accuracy:.7923,weightedF1:.7918,description:'Random forest text classifier.'},
{name:'Naive Bayes',type:'Classical ML',macroF1:.5331,accuracy:.8605,weightedF1:.8541,description:'Probabilistic sparse-text baseline.'},
{name:'LSTM',type:'Deep Learning',macroF1:.4778,accuracy:.7257,weightedF1:.7764,description:'Unidirectional LSTM classifier.'},
{name:'BiSimpleRNN',type:'Deep Learning',macroF1:.4492,accuracy:.7051,weightedF1:.7348,description:'Bidirectional simple recurrent network.'},
{name:'SimpleRNN',type:'Deep Learning',macroF1:.3575,accuracy:.6282,weightedF1:.6722,description:'Simple recurrent baseline.'}];
export const configs=[
['Logistic Regression','Config 1',.7769,.4860,.7921,'C=1 · saga · max_iter=1000'],['Logistic Regression','Config 2',.8314,.5713,.8359,'C=2 · saga · max_iter=1000'],['Logistic Regression','Config 3',.8561,.5746,.8613,'C=4 · saga · max_iter=1000'],['BiGRU','Config 1',.8158,.5908,.8347,'units=128 · dropout=.30 · lr=.001 · batch=128'],['BiGRU','Config 2',.7535,.5329,.7817,'units=128 · dropout=.50 · lr=.001 · batch=128'],['BiGRU','Config 3',.8023,.5724,.8252,'units=256 · dropout=.30 · lr=.0005 · batch=128'],['LSTM','Config 1',.7441,.4864,.7720,'units=128 · dropout=.30 · lr=.001 · batch=128'],['LSTM','Config 2',.7013,.4255,.7376,'units=128 · dropout=.50 · lr=.001 · batch=128'],['LSTM','Config 3',.7285,.4651,.7607,'units=256 · dropout=.30 · lr=.0005 · batch=128']].map(([model,config,accuracy,macroF1,weightedF1,params])=>({model,config,accuracy,macroF1,weightedF1,params}));
